env:
    browser: true
    es6: true
extends:
    - eslint:all
    - plugin:@typescript-eslint/all
    - prettier/@typescript-eslint
    - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 6
    project: tsconfig.json
    sourceType: module
# https://github.com/eslint/eslint/tree/master/docs/rules
# https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules
rules:
    "@typescript-eslint/consistent-type-definitions": off
    "@typescript-eslint/consistent-type-imports": off
    "@typescript-eslint/explicit-function-return-type":
        - error
        - allowExpressions: true
          allowTypedFunctionExpressions: true
    "@typescript-eslint/no-magic-numbers": off
    "@typescript-eslint/no-parameter-properties": off
    "@typescript-eslint/no-type-alias": off
    "@typescript-eslint/prefer-readonly-parameter-types": off
    "@typescript-eslint/restrict-template-expressions":
        - error
        - allowBoolean: true
          allowNullable: true
          allowNumber: true
    # enforced through tsconfig
    "@typescript-eslint/typedef": off
    capitalized-comments: off
    complexity: off
    consistent-return: off
    eqeqeq:
        - error
        - smart
    func-style: off
    id-length:
        - error
        - exceptions:
              - i
              - _
    lines-between-class-members:
        - error
        - always
        - exceptAfterSingleLine: true
    max-classes-per-file: off
    max-statements: off
    multiline-comment-style: off
    no-console:
        - error
        - allow:
              - error
    no-continue: off
    no-else-return: off
    no-eq-null: off
    no-lonely-if: off
    no-ternary: off
    no-undefined: off
    no-void: off
    no-warning-comments: off
    one-var:
        - error
        - never
    prettier/prettier: error
    sort-imports: off
