image: node:14.15.4

cache:
  paths:
    - .pnpm-store/

ci:
  variables:
    npm_config_store_dir: .pnpm-store
  before_script:
    - npm install -g pnpm
  script:
    - pnpm install --frozen-lockfile
    - pnpm build
    - pnpx git-is-clean
  after_script:
    - pnpm store prune
