image: node:15.14.0-alpine

cache:
  paths:
    - .pnpm-store/

variables:
  # can't cache outside project dir, so override the default to cache the store
  npm_config_store_dir: .pnpm-store
  npm_config_side_effects_cache: "true"

ci:
  except:
    - schedules
  script:
    # necessary with alpine's minimal image
    - apk add --no-cache git make python util-linux
    # pnpm does not come bundled
    - npm install -g pnpm
    - pnpm install --frozen-lockfile
    - pnpm build
    - pnpx git-is-clean

prune:
  only:
    - schedules
  script:
    - rm -rf .pnpm-store
