image: node:14.12.0

cache:
    paths:
        - node_modules/

ci:
    before_script:
        - yarn install --frozen-lockfile
    script:
        - yarn build
    after_script:
        - npx git-is-clean
