image: node:10.20.1-alpine

install-build-verify:
    before_script:
        - "apk add git"
    script:
        - "yarn install --frozen-lockfile"
        - "yarn build"
    after_script:
        - "npx git-is-clean"
