arrowParens: avoid
bracketSpacing: false
htmlWhitespaceSensitivity: ignore
overrides:
  - files: "*.{md,yml}"
    options:
      tabWidth: 2
printWidth: 160
proseWrap: never
tabWidth: 4
trailingComma: none
